### ISSUE TITLE
"HTTP Error 404: Not Found" when collecting ICANN emails

### ISSUE THREAD

**Issue by sbenthall** [nllz/bigbang#12]
Running this script:

`python2 bin/collect_mail.py -f examples/mm.icann.org.txt`

gets me this stack trace:

```
'retrieving http://mm.icann.org/pipermail/absdt2011-January.txt.gz'
Traceback (most recent call last):
  File "bin/collect_mail.py", line 41, in <module>
    main(sys.argv[1:])
  File "bin/collect_mail.py", line 38, in main
    mailman.collect_from_file(arg)
  File "/home/sb/projects/nllz-bigbang/bigbang/bigbang/mailman.py", line 94, in collect_from_file
    collect_from_url(url)
  File "/home/sb/projects/nllz-bigbang/bigbang/bigbang/mailman.py", line 80, in collect_from_url
    collect_archive_from_url(url)
  File "/home/sb/projects/nllz-bigbang/bigbang/bigbang/mailman.py", line 142, in collect_archive_from_url
    resp = urllib2.urlopen(gz_url)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/sb/anaconda/envs/nllz/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

```

**Comment by sbenthall** [comment]
URL for the archive file is being constructed incorrectly. The correct URL is:

`http://mm.icann.org/pipermail/absdt/2011-January.txt.gz`

Note the slash, not das, between `absdt` and `2011`.

**Comment by nllz** [comment]
Nice find!

**Comment by sbenthall** [comment]
https://github.com/nllz/bigbang/commit/1a628bf55034977a1fd8b63f26585488c16b2b4e
